/*
 * sync_parse - reading the signed code set.
 *
 * Pure C99. The body is plain text, one record per line, so it can be
 * generated by a shell script today and a backend later without the
 * device noticing:
 *
 *   portao-sync v1
 *   gate <device-id>
 *   gen <generation>
 *   code <id> <hash-hex> <from> <until>
 *   code ...
 *   end
 *   mac <hex>
 *
 * The MAC covers everything up to and including the "end" line, newline
 * included. Signing a terminator rather than stopping at the last code
 * means a truncated body cannot verify: an attacker who cuts the file
 * after the second code would otherwise deliver a valid signature over
 * a shorter set, silently revoking the rest.
 *
 * Text rather than JSON on purpose: no parser dependency, one obvious
 * byte range to sign, and a file a person can read when something is
 * wrong at three in the morning.
 */
#ifndef SYNC_PARSE_H
#define SYNC_PARSE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "sync_logic.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SYNC_BODY_MAX 2048
#define SYNC_MAC_HEX_LEN 64
#define SYNC_GATE_ID_MAX 32

typedef enum {
    SYNC_PARSE_OK = 0,
    SYNC_PARSE_FORMAT,    /* not the right shape */
    SYNC_PARSE_VERSION,   /* a version this build does not speak */
    SYNC_PARSE_GATE,      /* addressed to a different gate */
    SYNC_PARSE_MAC,       /* signature does not verify */
    SYNC_PARSE_TRUNCATED, /* no end marker: the body was cut short */
    SYNC_PARSE_ENTRY,     /* a code line that cannot be trusted */
    SYNC_PARSE_TOO_MANY,  /* more codes than we can hold */
} sync_parse_result_t;

/* As tg_proto: injected so this file needs no crypto library. */
typedef bool (*sync_mac_fn)(const char *signed_region, size_t len,
                            char out_hex[SYNC_MAC_HEX_LEN + 1], void *user);

/* Parses and authenticates a response body.
 *
 * `gate_id` is this device's id; a body addressed to another gate is
 * refused, so one mis-pointed URL cannot load a neighbour's codes.
 *
 * The signature is checked before any code line is believed. */
sync_parse_result_t sync_parse(const char *body, const char *gate_id, sync_mac_fn mac,
                               void *user, sync_set_t *out);

const char *sync_parse_text(sync_parse_result_t r);

#ifdef __cplusplus
}
#endif

#endif /* SYNC_PARSE_H */
